# Generated by Django 5.2 on 2025-05-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_alter_flatlisting_rent_amount_alter_listing_creator_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="contact_number",
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name="listing",
            name="size",
            field=models.PositiveIntegerField(help_text="Number of people"),
        ),
    ]
