# Generated by Django 5.2 on 2025-05-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_listing_contact_number_alter_listing_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingimage',
            name='caption',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
