# Generated by Django 5.2 on 2025-05-13 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_flatlisting_initial_images_finalized_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flatlisting',
            name='initial_images_finalized',
        ),
        migrations.RemoveField(
            model_name='groupformationpost',
            name='initial_images_finalized',
        ),
        migrations.RemoveField(
            model_name='listingimage',
            name='caption',
        ),
        migrations.AlterField(
            model_name='listing',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
    ]
