# Generated by Django 5.2 on 2025-05-13 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_flatlisting_initial_images_finalized_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flatlisting',
            name='initial_images_finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupformationpost',
            name='initial_images_finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='flatlisting',
            name='rent_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
